apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: medflow
  labels:
    app: backend
spec:
  type: ClusterIP  # Service accessible uniquement dans le cluster
  selector:
    app: backend  # Sélectionne les pods avec le label "app: backend"
  ports:
  - port: 80        # Port du service (accessible via ce port)
    targetPort: 4000 # Port du conteneur (où l'app écoute)
    protocol: TCP
    name: http

