apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: medflow
spec:
  accessModes:
    - ReadWriteOnce  # Un seul pod peut monter en écriture
  resources:
    requests:
      storage: 10Gi  # Taille demandée (10 Go)
  storageClassName: standard  # Type de stockage (Minikube utilise "standard")

