apiVersion: v1
kind: Secret
metadata:
  name: medflow-secrets
  namespace: medflow
type: Opaque
data:
  # JWT Secret Key (base64 encoded)
  jwt-secret-key: ZGZlcmV0YnZkZmJydHloeXludWlrZA==
  
  # MongoDB URI (base64 encoded) - MongoDB local Kubernetes
  mongo-uri: bW9uZ29kYjovL2FkbWluOk1lZEZsb3cyMDI0U2VjdXJlIUBtb25nb2RiLXNlcnZpY2U6MjcwMTcvTWVGbG93Mj9hdXRoU291cmNlPWFkbWlu
  
  # MongoDB Password pour StatefulSet local (base64 encoded)
  mongo-password: TWVkRmxvdzIwMjRTZWN1cmUh
  
  # Cloudinary Configuration (base64 encoded)
  cloudinary-cloud-name: ZGFxdm5mc285
  cloudinary-api-key: MjkzNDg4MjQzNTg2NDU3
  cloudinary-api-secret: ZUgyb2ZmRnBGaTJwa2hCRG1HRWJReGVWcnhZ

